project:
  type: book
  output-dir: docs

book:
  title: "CNN Change Detection"
  subtitle: "Master of Data Science"
  affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2022-08-26"
  page-footer:
    left: "Copyright 2022, Denis Berroeta"
  chapters:
    - index.qmd
    - intro.qmd
    - marco.qmd
    - rev_biblio.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css
    fig-cap-location: "margin"
    tab-cap-location: "bottom"
    fig-align: "center"
    mailto: "denis.berroeta@uai.cl"
  pdf:
    documentclass: scrreprt



