# Estado del Arte {#sec-estado .unnumbered}



Entre las aplicaciones de la Percepción Remota, la detección de cambios tiene como objetivo reconocer la información modificada de una misma región mediante el análisis de imágenes mutlitemporales. En los últimos años ha despertado un gran interés [@amitrano_2021]. \sm{LA ULTIMA FRASE ES COMO DESCONECTADA, MENCIONA QUE TE ENFOCARAS EN LOS SATELIATES SAR Y AGREGA UN POCO MAS}

En un proceso general de detección de cambios SAR, primero se crea la imagen de diferencia (DI), y la DI se clasifica en píxeles cambiados o no cambiados de forma supervisada o no supervisada [@Kumari_2016]. \SM{BASADO EN ESTA FRASE ME IMAGINO QUE HABLARAS DE METODOS USPERVISADOS Y NO SUPERVISADOS, PERO COMIENZAS A AHBLAR DE DETECCION DE RUIDO, CAMBIANDO EL ENFOQUE DEL PARRAFO EN FORMA BASTANTE GRANDE.} Sin embargo, la existencia de ruido de moteado es un problema no despreciable en la tarea de detección de cambios SAR. El ruido moteado (speckle) en imágenes SAR aparece como una forma de ruido multiplicativo y degrada la calidad de la imagen. Normalmente se producen falsas alarmas debido a la existencia de ruido speckle [@Wu_2019]. Por lo tanto, la clasificación de DI para imágenes SAR sigue siendo una tarea difícil [@Pham_2016]. Por lo tanto \SM{USAS DOS VECES POR LO TANTO}, es crítico diseñar técnicas robustas de detección de cambios que sean efectivas en la supresión del ruido de moteado (speckle) [@Saha_2021]. \SM{JUNTAS CON EL PROBLEMA}

En los últimos años, los investigadores han dedicado grandes esfuerzos a resolver o paliar el efecto del ruido de moteado. Existen dos tipos de técnicas de detección de cambios: métodos supervisados y no supervisados. En comparación, los métodos no supervisados son más populares ya que comparan dos imágenes SAR multitemporales sin ningún conocimiento previo o muestras etiquetadas manualmente [@gong_feature_2017]. \SM{FALTA DESCRIPCION DE LOS METODOS NO SUPERVIDAOS Y UNO QUE OTRO PAPER. OTRA FORMA DE ABORDAR ESTO ES DECIR QUE DE LOS NO SUPERVISADOS YA NO SE PESCAN Y QUE SOLO TE ENFOCAS EN LOS SUPERVISADOS. AL SER UN ESTADO DEL ARTE ESPERARIA MAS DETALLES DE ESTOS METODOS NO SOLO UN PAPER}

Los métodos existentes de detección de cambios sin supervisión se centran principalmente en la generación y clasificación de DI. En la generación de DI se utilizan los operadores log-ratio [@Bovolo_2005], Gauss-ratio  [@Hou_2014] o neighborhood-based ratio [@Gong_2012]. Además, se utiliza el coeficiente de variación basado en series temporales de imágenes SAR para evitar el ruido de moteado [@jiang_delineation_2020]. Para la clasificación de DI, se han empleado muchos métodos de clustering, como fuzzy c-means (FCM) [@Mishra_2012], k- means clustering [@Celik_2009], multiple kernel clustering [@Jia_2016], y algoritmo  de mean-shift  [@Aiazzi_2013]. Además, los métodos de aprendizaje automático basados en campos aleatorios de Markov también se aplican a la tarea del moteado [@bruzzone_automatic_2000]. 
\SM{ARREGLAS LAS CITAS, NO DEBERIA HABER ESPACIO. NO HAY HISTORIA, PARECE ESTADO DEL ARTE DE UN PAPER CORTO DONDE SOLO SE DICEN LOS METODOS.}


Para mejorar aún más el rendimiento de la clasificación DI, los investigadores incorporan clasificadores basados en aprendizaje profundo al modelo tradicional no supervisado. Gong et al.  asignaron primero pseudoetiquetas a los píxeles en DI mediante un clasificador conjunto basado en FCM ([@gong_change_2016]. A continuación, se entrenaron máquinas de Boltzmann restringidas (RBM) para la generación de mapas de cambio. Hou et al. [@Hou_2017] presentaron un método de detección de cambios combinando el cálculo de saliencia y el algoritmo de bajo rango. Zhan et al. [@Zhan_2017] propusieron un modelo CNN siamés profundo para extraer características discriminantes para la detección de cambios. Zhang et al. [@Zhang_2021] presentaron una CNN profunda de co-ocurrencia espacio-temporal de nivel de gris, que es capaz de explotar la información espacio-temporal de imágenes mutlitemporales. Dong et al. [@Dong_2022] integraron clustering no supervisado con CNN para aprender representaciones de características amigables con el clustering a partir de imágenes SAR multitemporales. Qu et al. [@Qu_2021] propusieron una red de dominio dual. Las características de los dominios de frecuencia y espacial se explotan para mitigar el ruido de moteado.

\sm{LO MISMO DE ARRIBA}