

# Problema u Oportunidad {#sec-problema .unnumbered} 



La degradación de los sistemas naturales ha sido catalogada como uno de los grandes problemas de la humanidad [@steffen2015]. Los estados alrededor del mundo han sido incapaces de detener estas tendencias presentando constantes de pérdida de bosque nativo, intervención de humedales y un aumento en la contaminación de aire, agua y vegetación. Por lo tanto, es indispensable monitorear de manera continua los recursos territoriales en los países, para así mejorar su gestión y cuidado.

\SM{CREO QUE FALTA FRASE QUE CONECTE CON LO DE ARRIBA O CAMBIAR UN POCO DLO DE ARRIBA}
El bosque y matorral esclerófilo de Chile es uno de los hotspot mundiales de biodiversidad debido a su gran cantidad de especies endémicas [@myers2000]. Estos ambientes han sido tradicionalmente amenazados y su cobertura ha sido reemplazada por otros usos productivos, como la industria forestal o la producción agrícola [@miranda2017]. 

\SM{FALTA FRASE DE CONECXION ENRTE PARRAFOS}

Monitorear los humedales es desafiante ya que son sistemas en constante cambio debido al efecto de inundaciones y sus procesos internos [@gallant2015]. Esto hace que analizar series de datos temporales sea complejo, ya que cambios en la señal satelital puede ser debido a estos factores y no a una perturbación que se necesite fiscalizar. \SM{NO PROFUNDIZAS EN LOS PARRAFOS SON COMO IDEAS DESCONECTADAS ENTRE SI, PARTE SUPER BIEN LA IDEA Y LUEGO TERMINA LA FRASE}

Entre los desafíos más relevantes se encuentran para las instituciones del estado para una eficiente fiscalización y protección de ecosistemas protegidos se encuentran \SM{NO SE ENTIENDE NADA}: a) la limitada capacidad de la institución para desarrollar proyectos de este tipo, con alrededor de dos aplicaciones por año (número por debajo a la demanda existente); y b) el procesamiento de las imágenes satelitales sigue siendo costoso. Esto último se debe a que incluso cuando se ha privilegiado el uso de datos libres y herramientas de procesamiento en la nube, con un nivel de automatización que aún no alcanza la madurez. Por lo anterior, se hace necesario diseñar y crear sistemas de monitoreo robustos metodológicamente y eficiente, con capacidad de escalamiento. 

El análisis de imágenes satelitales permite obtener datos espaciales de manera masiva y remota a lo largo de todo el país y permiten generar alertas de cambios ambientales, bajo una arquitectura de clasificación no supervisada, utilizando principalmente datos de SAR, e.g. Sentinel-1, ya que permite identificar el grado de humedad del humedal y a evitar problemas con la alta presencia de días nublados en el sur del país (i.e., los datos de SAR son capaces de atravesar las nubes, por lo que el clima no es un problema para su uso e implementación) \SM{MUY LARGA LA FRASE ME PERDI DE LA IDEA}. Sin embargo, la combinación e integración de estos dos tipos de datos satelitales es poco común, por lo que no hay metodologías estándares para implementar de forma directa para cada situación [@gallant2015]. 

En los últimos años, las redes neuronales convolucionales (CNN) han mejorado mucho el rendimiento de muchas tareas visuales. Se ha demostrado que es bastante eficaz para el aprendizaje robusto de características. Los modelos basados en CNN se han aplicado con éxito en la detección de cambios en imágenes de teledetección [@bazi2006,wang2022]. En este sentido, [@gong2012] propone un marco de CNN de extremo a extremo \sm{QUE SIGNIFINCA DE EXTRENMO A EXTREMO?} para aprender características discriminativas de la matriz de afinidad mixta para la detección de cambios.


Considerando los objetivos de la presente tesis es desarrollar un método automatizado de detección en tiempo real de cambios en la estructura de la vegetación de humedales urbanos, turberas y bosque esclerófilo basado en productos satelitales y algoritmos de inteligencia artificial, a modo de trabajos futuros y si los resultados de detección de cambios automatizados son suficientemente precisos y suficientemente eficiente, estos serán insumos para un siguiente sistema identifique y segmente la zona que se considera como un cambio resultante por intervención humana, puedan ser visualizados en una plataforma de monitoreo que apoye la gestión de Superintendencia del Medio Ambiente, como sistema de aleta temprana. 
\SM{MEJORAR PARRAFO, SERE SINCERO, NI SIQUIERA ME LO LEI, YA QUE ES UNA PURA ORACION.}

